/**
 * ManageSpace Audit API
 * ManageSpace Audit API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuditEntryResponse { 
    /**
     * Organization Id
     */
    orgId: string;
    /**
     * Site Id
     */
    siteId?: string;
    /**
     * User Id
     */
    userId: string;
    /**
     * Description of the Audit Entry.
     */
    description: string;
    /**
     * The service that produced the Audit Entry.
     */
    source?: string;
    /**
     * ID of the affected Entity.
     */
    entityId?: string;
    /**
     * The type of the affected Entity.
     */
    entityType?: string;
    /**
     * The date the change was made.
     */
    date: string;
    /**
     * The type of operation that happened on the affected Entity.
     */
    operationType?: string;
    /**
     * Any additional data relating to the Audit Entry.
     */
    metaData?: object;
    /**
     * The state of the entity before the operation was performed.
     */
    dataBefore?: object;
    /**
     * The state of the entity after the operation was performed.
     */
    dataAfter?: object;
}

